### ISSUE TITLE
The tool adds unnecessary slashes in crontitor.io URLs

### ISSUE THREAD

**Issue by Swop** [jonlives/autocronitor#1]
After running autocronitor, the generated cronjobs have errors in the generated cronitor.io URLs (before the HTTP scheme).

This leads to an error when executing the command.

Ex: (generated cronjob):

```
curl /https://cronitor.link/rHQ0qq/run -m 10 && SYMFONY_ENV=prod /var/www/webfronts/prod/Incubart/console/alittlemarket framework:clear-nonce-table >> /var/log/cron/api_clearNonceTable_alittlemarket.stdout 2>&1 && touch /tmp/api_clearNonceTable_alittlemarket.job && curl /https://cronitor.link/rHQ0qq/complete -m 10
```

We have `curl /https://cronitor.link/rHQ0qq/run` instead of `curl https://cronitor.link/rHQ0qq/run`

**Comment by jonlives** [comment]
Thanks @Swop, just fixed that error and released a new version

**Comment by Swop** [comment]
Great!
